version: '2'
services:
    sebhipster-app:
        image: sebhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sebhipster-mysql:3306/sebhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sebhipster-mysql:
        extends:
            file: mysql.yml
            service: sebhipster-mysql
